### ISSUE TITLE
asset file digest in importmap script tag doesn't refresh after change since version 0.6

### ISSUE THREAD

**Issue by meceo** [rails/importmap-rails#34]
While developing, changes in js files are properly noticed by listen gem. New digest for changed file is generated. However, the script tag of importmap still contains old digest. Multiple refreshes don't help. Only after server restart the new digests are noticed and used by importmap.

The issue does not exists on version to 0.5.3.

**Comment by tleish** [comment]
Found the same issue

**Comment by dhh** [comment]
Are you precompiling assets in development? Otherwise it doesn't actually matter. The Sprockets asset server strips the digests regardless. And the default for Rails is not even to generate them in production via config.assets.digest = false.

This was changed such that we can cache the importmap in development and testing, and only invalidate it when there are changes made to config/importmap.rb.

But I could see how this might be confusing, and at the very least we should document it. First, though, let's confirm that it's not having any actual impact on the app.

**Comment by meceo** [comment]
I don't precompile assets in development. From your explanation I get that the digests doesn't change (on purpose), but the content of the file should change. However this is not the behaviour I experience. The file content stays unchanged until rails server is restarted

Flow example:
1. load a page with a js script file (in browser)
2. modify the js script file (in editor)
3. refresh the page with cmd + R (in browser)
4. the file content didn't change (in browser + chrome dev tool)
5. the importmap in the page source code lists the file with old digest (in browser)
6. click on the js file to open for investigation (in browser)
7. the file source code opens with old content (in browser)
8. refresh the the file source code (cmd + R) and from now on it returns 404 (in browser)
9. go back to the page and refresh (in browser)
10. get 404 for the js file request until restart the server

**Comment by dhh** [comment]
That's annoying. I suppose Sprockets actually does verify the digest, even though it doesn't have to. I'll have a look at restoring the cached behavior for now. Thanks for breaking this down!

**Comment by ghiculescu** [comment]
FYI, another instance of this here https://github.com/rails/rails/issues/43264

**Comment by ghiculescu** [comment]
Confirmed that setting `config.assets.digest = false` in `development.rb` makes the issue go away, on the replication app from https://github.com/rails/rails/issues/43264 (https://github.com/nateberkopec/nonsense). Probably not that helpful though since I don't think that's a good setting to use in development.

**Comment by ghiculescu** [comment]
@dhh what do you think about reverting these changes for now? 

![image](https://user-images.githubusercontent.com/509837/134028272-2985f00a-7679-4eb8-bc76-9bea5216344b.png)

It is just bad timing, because the version of `importmap-rails` that gets installed with the Rails alpha has this issue and I imagine it's going to confuse lots of people.

**Comment by dhh** [comment]
Fixed via https://github.com/rails/importmap-rails/commit/56db58a5beeb970452721bda65cdc053d85e1a45 which was released in 0.7.0.

**Comment by dkniffin** [comment]
@dhh I'm still seeing this same behavior on 1.1.5. With `config.assets.digest = true`, changes don't update the importmap to have a new digest. `config.assets.digest = false` makes the problem go away.

The file I'm testing with is `app/javascript/js_tests.js`, so it should be matched your commit above.

I also verified `Rails.application.config.importmap.sweep_cache` is `true`
